apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-gitops-info
  namespace: openshift-gitops-operator
data:
  environment: "dev"
  clusterName: '{{hub .ManagedClusterName hub}}'
  apiServerURL: '{{hub (index (lookup "cluster.open-cluster-management.io/v1" "ManagedCluster" "" .ManagedClusterName).spec.managedClusterClientConfigs 0).url hub}}'
