apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: gitops-operator-channel-dev
  namespace: dev-apps
spec:
  type: Git
  pathname: https://github.com/<your-org>/acm-openshift-gitops-install.git
